[package]
name = "xclock"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "processthreadsapi","sysinfoapi", "wingdi", "commctrl"] }
chrono = { version = "0.4", features = ["serde"] }

